export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILURE = "GET_USER_FAILURE";

export const GET_DIMENSION = "GET_DIMENSION";
export const SET_DIEMNSION = "SET_DIEMNSION";



export const GET_LINEDATA = "GET_LINEDATA";
export const SET_LINEDATA = "SET_LINEDATA";
export const RESET_LINEID = "RESET_LINEID";
export const DELETEBY_LINEID = "DELETEBY_LINEID";

export const GET_CHARTPROP = "GET_CHARTPROP";
export const SET_CHARTPROP = "SET_CHARTPROP";
export const SET_ZOOMSTATE = "SET_ZOOMSTATE";
export const SET_ZOOMXZSTATE = "SET_ZOOMXZSTATE";
export const SET_ZOOMYZSTATE = "SET_ZOOMYZSTATE";

